language: python
python:
 - 3.7.4

addons:
  apt:
    packages:
      - libffi-dev
      
install:
  # Thanks to The Unfun Cat for explaining how to set up .travis.yml with both R and Python using conda
  # https://stackoverflow.com/questions/44317627/installing-both-python-and-r-for-a-travis-build
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels bioconda
  - conda config --add channels r
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest codecov numpy pandas matplotlib tzlocal h5py pytables libffi
  - source activate test-environment
  - conda install -c conda-forge rpy2
  - python --version
  - pip install spectral
  - R --version
  - echo "install.packages('scales', repos = 'http://cran.us.r-project.org')" > R_scales_install.R
  - chmod ugo+rwx R_scales_install.R
  - Rscript R_scales_install.R
  - pip install ".[test]" . # install package + test dependencies
script: pytest
after_success:
  - codecov # submit coverage
