language: python
python:
 - 3.7.4
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install numpy
  - pip install pandas
  - pip install spectral
  - pip install rpy2
  - pip install matplotlib
  - sudo apt -y install r-base
  - wget https://cran.r-project.org/src/contrib/scales_1.1.1.tar.gz
  - R CMD INSTALL scales_1.1.1.tar.gz
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
