name: test-environment
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - python
  - pytest
  - codecov
  - numpy
  - pandas
  - matplotlib
  - tzlocal
  - h5py
  - pytables
  - libffi
  - rpy2
  - r-scales
