package:
  name: gmodetector_py
  version: 0.63.1

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  host:
    - python
  run:
    - python 3.9.*
    - pytest
    - codecov
    - numpy
    - pandas
    - matplotlib
    - tzlocal
    - h5py
    - pytables
    - libffi
    - rpy2
    - r-scales

test:
  imports:
    - gmodetector_py

about:
  home: https://github.com/naglemi/gmodetector_py 
  license: BSD-3
  license_file: LICENSE 
  summary: Python CPU implementation of GLM for quantifying fluorophores in fluorescent hyperspectral images

extra:
  recipe-maintainers:
    - naglemi
