name: Python CI with Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda and Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-environment
        environment-file: environment.yml
        python-version: 3.7.4
        auto-activate-base: false
        channels: bioconda,r,conda-forge

    - name: Additional Environment Setup
      run: |
        conda install -c conda-forge rpy2
        pip install spectral
        echo "install.packages('scales', repos = 'http://cran.us.r-project.org')" > R_scales_install.R
        chmod ugo+rwx R_scales_install.R
        Rscript R_scales_install.R
        pip install ".[test]" .

    - name: Test with pytest
      run: pytest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
