name: Python CI with Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python and Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.7.4
        channels: bioconda,r
        auto-activate-base: false

    - name: Create and Activate Conda Environment
      shell: bash -l {0}
      run: |
        env_path=$GITHUB_WORKSPACE/env
        conda create --prefix $env_path python=3.7.4 pytest codecov numpy pandas matplotlib tzlocal h5py pytables libffi
        echo "$env_path/bin" >> $GITHUB_PATH

    - name: Install Additional Dependencies
      shell: bash -l {0}
      run: |
        conda activate $GITHUB_WORKSPACE/env
        conda install -c conda-forge rpy2
        pip install spectral
        echo "install.packages('scales', repos = 'http://cran.us.r-project.org')" > R_scales_install.R
        chmod ugo+rwx R_scales_install.R
        Rscript R_scales_install.R
        pip install ".[test]" .

    - name: Run Tests
      shell: bash -l {0}
      run: |
        conda activate $GITHUB_WORKSPACE/env
        pytest --ignore=$GITHUB_WORKSPACE/env/lib/python3.7/site-packages/matplotlib/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
