name: Python CI with Conda and Anaconda Package Publishing

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python and Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        channels: conda-forge,bioconda,r
        auto-activate-base: true

    - name: Create and Activate Conda Environment
      shell: bash -l {0}
      run: |
        env_path=$GITHUB_WORKSPACE/env
        conda create --prefix $env_path python=3.9
        echo "$env_path/bin" >> $GITHUB_PATH

    - name: Install dependencies from environment.yml
      shell: bash -l {0}
      run: |
        conda env update --file environment.yml --name base

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda install pytest
        pytest

    - name: Build Conda package
      shell: bash -l {0}
      run: |
        conda install conda-build
        conda build .

    - name: Publish to Anaconda
      shell: bash -l {0}
      run: |
        conda install anaconda-client
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $GITHUB_WORKSPACE/env/conda-bld/linux-64/*.tar.bz2
