name: Python CI with Conda and Anaconda Package Publishing

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}  # Use the same shell throughout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev
        sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

    - name: Create and Activate Conda Environment
      shell: bash -l {0}
      run: |
        env_path=$GITHUB_WORKSPACE/env
        conda create --prefix $env_path python=3.9 pytest codecov numpy pandas matplotlib tzlocal h5py pytables
        echo "$env_path/bin" >> $GITHUB_PATH

    - name: Install Additional Dependencies
      shell: bash -l {0}
      run: |
        conda activate $GITHUB_WORKSPACE/env
        conda install -c conda-forge rpy2
        pip install spectral
        echo "install.packages('scales', repos = 'http://cran.us.r-project.org')" > R_scales_install.R
        chmod ugo+rwx R_scales_install.R
        Rscript R_scales_install.R
        pip install ".[test]" .

    - name: Run Tests
      shell: bash -l {0}
      run: |
        conda activate $GITHUB_WORKSPACE/env
        pytest --ignore=$GITHUB_WORKSPACE/env/
        
    - name: Build Conda package
      run: |
        conda activate $GITHUB_WORKSPACE/env
        conda install conda-build
        conda build .

    - name: Publish to Anaconda
      run: |
        conda activate $GITHUB_WORKSPACE/env
        conda install anaconda-client
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload $GITHUB_WORKSPACE/env/conda-bld/linux-64/*.tar.bz2
